DROP TABLE IF EXISTS eais;

CREATE TABLE eais (
	MGM_BLDRGST_PK VARCHAR(255), --관리_건축물대장_PK
	BYLOT_CNT INT, --외필지_수
	SIGUNGU_CD VARCHAR(255), --시군구_코드
	REGSTR_KIND_CD VARCHAR(255), --대장_종류_코드
	JIGU_CD_NM VARCHAR(255), --지구_코드_명
	REGSTR_KIND_CD_NM VARCHAR(255), --대장_종류_코드_명
	NA_ROAD_CD VARCHAR(255), --새주소_도로_코드
	NEW_PLAT_PLC VARCHAR(255), --도로명_대지_위치
	NA_UGRND_CD VARCHAR(255), --새주소_지상지하_코드
	REGSTR_GB_CD_NM VARCHAR(255), --대장_구분_코드_명
	BUN VARCHAR(255), --번
	GUYUK_CD_NM VARCHAR(255), --구역_코드_명
	GUYUK_CD VARCHAR(255), --구역_코드
	NA_MAIN_BUN INT, --새주소_본_번
	REGSTR_GB_CD VARCHAR(255), --대장_구분_코드
	BLD_NM VARCHAR(255), --건물_명
	CRTN_DAY VARCHAR(255), --생성_일자
	NA_BJDONG_CD VARCHAR(255), --새주소_법정동_코드
	SPLOT_NM VARCHAR(255), --특수지_명
	BLOCK VARCHAR(255), --블록
	JIYUK_CD_NM VARCHAR(255), --지역_코드_명
	NA_SUB_BUN INT, --새주소_부_번
	JIYUK_CD VARCHAR(255), --지역_코드
	LOT VARCHAR(255), --로트
	MGM_UPPER_BLDRGST_PK VARCHAR(255), --관리_상위_건축물대장_PK
	JIGU_CD VARCHAR(255), --지구_코드
	BJDONG_CD VARCHAR(255), --법정동_코드
	PLAT_GB_CD VARCHAR(255), --대지_구분_코드
	PLAT_PLC VARCHAR(255), --대지_위치
	JI VARCHAR(255), --지"	

	PRIMARY KEY(MGM_BLDRGST_PK)
);
